name: CD
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: build images and push to docker hub
        uses: docker/build-push-action@v1.1.0
        with:
          username: hattodevops
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: hattodevops/goapp
          tags: ${{ github.sha }}, latest
